export interface adminPlan {
    breakfastFood:string,
    foodDate: Date,
    lunchFood: string,
    dinnerFood: string,
    snacks?: string,
    breakfastKcal: number,
    lunchKcal: number,
    dinnerKcal: number,
    snacksKcal?: number,
    cardio?: string,
    cardioKcal?: number,
    resistance?: string,
    resistanceKcal?: number,
    submittedBy: string,
    memberEmail: string,
    notesReq: boolean,
    notes?: string,
}